#!/bin/sh

set -e

VERSION=0.2

reference="$1"
query="$2"

unset tmpdir
tmpdir=$(mktemp --tmpdir -d biodiff.XXXX)
refdir="$tmpdir/ref"
qrydir="$tmpdir/qry"

cleanup () {
    rm -rf "$tmpdir"
}

usage () {
    echo "Input error - Please see biodiff(1) for usage instructions."
    exit 1
}

check_inversions () {
    ref="$1"
    qry="$2"
    &> /dev/null nucmer --maxmatch -p "$tmpdir/inv" "$ref" "$qry"
    delta-filter -1 "$tmpdir/inv.delta" > "$tmpdir/inv.1filter.delta"
    REFERENCE="$ref" show-coords -HrTd "$tmpdir/inv.1filter.delta" \
	| perl -e "$(cat <<'EOF'
my ($refstart, $refstop, $qrystart, $qrystop, $refdirection, $qrydirection);

while(<>) {
	chomp;
	(
	$refstart, $refstop,
	$qrystart, $qrystop,
	undef, undef, undef,
	$refdirection, $qrydirection,
	$reftag, $qrytag,
	) = split("\t", $_);

	if (($refdirection ne $qrydirection) && ($reftag eq $qrytag)) {
		print join("\t", ($reftag,
		                  $refstart,
		                  ".",
		                  "",)
EOF
)"

}

read_fasta () {
    export outdir="$1"
    mkdir "$outdir"
    infile="$2"
    perl -e "$(cat <<'EOF'
open(my $filename, '>', '/dev/null');

while(<>) {
	chomp;
	if ( $_ =~ /^>\s*(\S+)/) {
		close($filename);
		open($filename, '>', "$ENV{'outdir'}/$1");
	} else {
		print $filename join("\n", split('', $_))."\n";
	}
}
EOF
    )" "$infile"
}

write_fasta () {
    dir="$1"
    outfasta="$2"
    ls "$dir/*" &> /dev/null && \
	for seq in "$dir/*"
	do
	    echo ">$(basename $seq)"
	    cat "$seq"
	done > "$outfasta"
}

trap cleanup EXIT

if [ -z "$reference" ] || [ -z "$query" ] || [ -n "$3" ]
then
    usage
fi

read_fasta "$refdir" $reference
read_fasta "$qrydir" $query

# If we have one reference and one query, don't require matching identifiers
if [ $(ls "$refdir" | wc -l) = 1 ] && [ $(ls "$qrydir" | wc -l) = 1 ]
then
    qry_id="$(basename "$qrydir/"*)"
    ref_id="$(basename "$refdir/"*)"
    if [ "$qry_id" != "$ref_id" ]
    then
	>&2 echo "Warning: The query ID does not match the reference ID."
	>&2 echo "         comparing them anyway because that's probably what you wanted..."
	>&2 echo "         Query ID: $qry_id"
	>&2 echo "         Reference ID: $ref_id"

	mv "$qrydir/$qry_id" "$qrydir/$ref_id"
    fi
fi

write_fasta "$refdir" "$refdir.fasta"
write_fasta "$qrydir" "$qrydir.fasta"

cat <<EOF
##fileformat=VCFv4.2
##source=biodiffV${VERSION}
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
EOF

check_inversions "$refdir.fasta" "$qrydir.fasta"

diff --ignore-case \
     --recursive \
     --unified=1 \
     --minimal \
     --ignore-blank-lines \
     "$refdir" "$qrydir" \
    | udiff2vcf
