#!/bin/sh

set -e

VERSION=0.1

reference="$1"
query="$2"

unset tmpdir
tmpdir=$(mktemp --tmpdir -d biodiff.XXXX)
refdir="$tmpdir/ref"
qrydir="$tmpdir/qry"

cleanup () {
    rm -rf "$tmpdir"
}

usage () {
    echo "Input error - Please see biodiff(1) for usage instructions."
    exit 1
}

read_fasta () {
    export outdir="$1"
    mkdir "$outdir"
    infile="$2"
    perl -e "$(cat <<'EOF'
open(my $filename, '>', '/dev/null');

while(<>) {
	chomp;
	if ( $_ =~ /^>\s*(\S+)/) {
		close($filename);
		open($filename, '>', "$ENV{'outdir'}/$1");
	} else {
		print $filename join("\n", split('', $_))."\n";
	}
}
EOF
    )" "$infile"
}

trap cleanup EXIT

if [ -z "$reference" ] || [ -z "$query" ] || [ -n "$3" ]
then
    usage
fi

read_fasta "$refdir" $reference
read_fasta "$qrydir" $query

cat <<EOF
##fileformat=VCFv4.2
##source=biodiffV${VERSION}
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
EOF

diff --ignore-case \
     --recursive \
     --unified=1 \
     --minimal \
     --ignore-blank-lines \
     "$refdir" "$qrydir" \
    | udiff2vcf
